#!/bin/bash
echo "Compiling read_button.cpp and GPIO.cpp into read_button.cgi"
g++ read_button.cpp GPIO.cpp -o read_button.cgi -lcgicc -pthread
echo "Configuring GPIO46 for in+"
config-pin -a p8.16 in+
echo "Done"
