#!/bin/bash
echo "Copying read_button.cgi to /usr/lib/cgi-bin"
sudo cp read_button.cgi /usr/lib/cgi-bin
echo "Adding s permission to /usr/lib/cgi-bin/read_button.cgi"
sudo chmod +s /usr/lib/cgi-bin/read_button.cgi
